---
- import_playbook: playbooks/01-wait-for-containers.yml
- import_playbook: playbooks/02-setup-base.yml
- import_playbook: playbooks/03-install-k3s.yml
- import_playbook: playbooks/04-setup-glusterfs.yml
- import_playbook: playbooks/05-install-haproxy.yml
