---
# Common variables
gateway: "10.11.4.253"
network_base: "10.11.4.0/24"

# k3s configuration
k3s_version: "latest"
k3s_token: ""

# GlusterFS configuration
glusterfs_volume_name: "shared-storage"
glusterfs_brick_path: "/gluster/brick"
glusterfs_mount_point: "/mnt/gluster"
glusterfs_replica_count: 3

# HAProxy configuration
haproxy_http_port: 80
haproxy_https_port: 443
haproxy_stats_port: 8404
